{
 "title": "AD and DNS",
 "description": "Active Directory and DNS Dashboard using Prometheus WMI_Exporter ",
 "tags": [
  "active directory",
  "domain",
  "dns",
  "windows",
  "prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "DNS Queries",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(wmi_dns_queries_total{protocol=\"udp\"}[1m]))"
    }
   ]
  },
  {
   "title": "DNS Queries/Sec",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(wmi_dns_queries_total{protocol=\"udp\"}[1m]))"
    }
   ]
  },
  {
   "title": "LDAP Searches",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(wmi_ad_ldap_searches_total{}[1m]))"
    }
   ]
  },
  {
   "title": "LDAP Searches / Sec",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(wmi_ad_ldap_searches_total{}[1m]))"
    }
   ]
  },
  {
   "title": "LDAP Connections/Sec",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(wmi_ad_ldap_opened_connections_total[1m]))"
    }
   ]
  },
  {
   "title": "LDAP Connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(wmi_ad_ldap_opened_connections_total[1m]))"
    }
   ]
  },
  {
   "title": "Pending Syncronisations",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(wmi_ad_replication_pending_synchronizations{})"
    }
   ]
  },
  {
   "title": "Pending Operations",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(wmi_ad_replication_pending_operations{})"
    }
   ]
  },
  {
   "title": "DNS Queries/Responses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(wmi_dns_queries_total{}[1m])",
     "legendFormat": "in-{{protocol}} ({{instance}})"
    },
    {
     "expr": "-delta(wmi_dns_responses_total{}[1m])",
     "legendFormat": "out-{{protocol}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Recursive Queries / Failures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(wmi_dns_recursive_query_failures_total[1m])",
     "legendFormat": "failures ({{instance}})"
    },
    {
     "expr": "delta(wmi_dns_recursive_queries_total[1m])",
     "legendFormat": "queries ({{instance}})"
    },
    {
     "expr": "delta(wmi_dns_recursive_query_send_timeouts_total[1m])",
     "legendFormat": "sent timeouts ({{instance}})"
    }
   ]
  },
  {
   "title": "Inbound Updates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(wmi_ad_replication_inbound_objects_updated_total{}[1m])",
     "legendFormat": "objects ({{instance}})"
    },
    {
     "expr": "delta(wmi_ad_replication_inbound_properties_updated_total{}[1m])",
     "legendFormat": "properties ({{instance}})"
    }
   ]
  },
  {
   "title": "Intrasite Replication Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "delta(wmi_ad_replication_data_intrasite_bytes_total{direction=\"inbound\"}[1m])",
     "legendFormat": "inbound ({{instance}})"
    },
    {
     "expr": "-delta(wmi_ad_replication_data_intrasite_bytes_total{direction=\"outbound\"}[1m])",
     "legendFormat": "outbound ({{instance}})"
    }
   ]
  },
  {
   "title": "Intersite Replication Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "delta(wmi_ad_replication_data_intersite_bytes_total{direction=\"inbound\"}[1m])",
     "legendFormat": "inbound ({{instance}})"
    },
    {
     "expr": "-delta(wmi_ad_replication_data_intersite_bytes_total{direction=\"inbound\"}[1m])",
     "legendFormat": "outbound ({{instance}})"
    }
   ]
  },
  { "title": "AD Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "AD Operations (Detailed)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(wmi_ad_directory_operations_total{}[1m])",
     "legendFormat": "{{origin}}-{{operation}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Directory Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(wmi_ad_database_operations_total{}[1m])",
     "legendFormat": "{{operation}} ({{instance}})"
    }
   ]
  },
  { "title": "AD Binds", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "AD Bind",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(wmi_ad_binds_total{}[1m])",
     "legendFormat": "{{bind_method}} ({{instance}})"
    }
   ]
  },
  { "title": "AD LDAP Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "LDAP Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "delta(wmi_ad_ldap_opened_connections_total{type=\"ldap\"}[1m])",
     "legendFormat": "Opened ({{instance}})"
    },
    {
     "expr": "-(delta(wmi_ad_ldap_closed_connections_total{}[1m]))",
     "legendFormat": "Closed ({{instance}})"
    }
   ]
  },
  {
   "title": "LDAP Searches/Updates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(wmi_ad_ldap_writes_total{}[1m])",
     "legendFormat": "Writes ({{instance}})"
    },
    {
     "expr": "-delta(wmi_ad_ldap_searches_total{}[1m])",
     "legendFormat": "Searches ({{instance}}"
    }
   ]
  },
  {
   "title": "DNS Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(wmi_dns_memory_used_bytes_total{}[5m])",
     "legendFormat": "{{area}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Updates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(wmi_dns_dynamic_updates_received_total[1m])",
     "legendFormat": "{{operation}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(wmi_dns_dynamic_updates_failures_total[1m])",
     "legendFormat": "{{reason}} ({{instance}})"
    }
   ]
  }
 ]
}