{
 "title": "Dell iDrac",
 "description": "Made by Hieu15",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(sysUpTime{company=\"ITFORVN\",type=\"iDrac\"}, hostname)"
   }
  ]
 },
 "panels": [
  { "title": "iDrac summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Local Time", "type": "grafana-clock-panel", "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 } },
  {
   "title": "Overview Linux",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "up{hostname=\"$node\"} == 1 or up{hostname=\"$node\"} == 0"
    },
    {
     "expr": "systemPowerState{hostname=\"$node\"}"
    },
    {
     "expr": "globalSystemStatus{hostname=\"$node\"}"
    },
    {
     "expr": "systemPowerUpTime{hostname=\"$node\"}"
    }
   ]
  },
  {
   "title": "Global Status Map",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "globalSystemStatus{hostname=\"$node\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "# of  iDrac",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(up{company=\"ITFORVN\",type=\"iDrac\"})"
    }
   ]
  },
  { "title": "Server basic information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(processorDeviceIndex{hostname=\"$node\"})"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(memoryDeviceSize{hostname=\"$node\"})"
    }
   ]
  },
  {
   "title": "RAM Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "systemStateMemoryDeviceStatusCombined{hostname=\"$node\"}"
    }
   ]
  },
  {
   "title": "FAN Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "\r\nsystemStateCoolingDeviceStatusCombined{hostname=\"$node\"}"
    }
   ]
  },
  {
   "title": "System Power",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "amperageProbeReading{hostname=\"$node\"} > 20",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "CPU cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(processorDeviceCoreCount{hostname=\"$node\"})"
    }
   ]
  },
  {
   "title": "Total Disk",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(physicalDiskCapacityInMB{hostname=\"$node\"})"
    }
   ]
  },
  {
   "title": "DISK Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "globalStorageStatus{hostname=\"$node\"}"
    }
   ]
  },
  {
   "title": "POWER SUPPLY 1",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "powerSupplyStatus{hostname=\"$node\", powerSupplyIndex=\"1\"}"
    }
   ]
  },
  {
   "title": "POWER State",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "systemPowerState{hostname=\"$node\"}"
    }
   ]
  },
  {
   "title": "BIOS Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "\r\nsystemBIOSStatus{hostname=\"$node\"}"
    }
   ]
  },
  {
   "title": "BATTERY Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "systemStateBatteryStatusCombined{hostname=\"$node\"}"
    }
   ]
  },
  {
   "title": "POWER SUPPLY 2",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "powerSupplyStatus{hostname=\"$node\", powerSupplyIndex=\"2\"}"
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "((temperatureProbeReading{hostname=\"$node\"}/10) + on (temperatureProbeIndex) group_left(temperatureProbeLocationName) (temperatureProbeLocationName{temperatureProbeIndex=\"3\"}))\nor \n((temperatureProbeReading{hostname=\"$node\"}/10) + on (temperatureProbeIndex) group_left(temperatureProbeLocationName) (temperatureProbeLocationName{temperatureProbeIndex=\"4\"}))\nor \n((temperatureProbeReading{hostname=\"$node\"}/10) + on (temperatureProbeIndex) group_left(temperatureProbeLocationName) (temperatureProbeLocationName{temperatureProbeIndex=\"5\"}))\nor \n((temperatureProbeReading{hostname=\"$node\"}/10) + on (temperatureProbeIndex) group_left(temperatureProbeLocationName) (temperatureProbeLocationName{temperatureProbeIndex=\"6\"}))",
     "legendFormat": "{{temperatureProbeLocationName}}"
    }
   ]
  },
  {
   "title": "Air Temp",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "((temperatureProbeReading{hostname=\"$node\"}/10) + on (temperatureProbeIndex) group_left(temperatureProbeLocationName) (temperatureProbeLocationName{temperatureProbeIndex=\"1\"}))\nor \n((temperatureProbeReading{hostname=\"$node\"}/10) + on (temperatureProbeIndex) group_left(temperatureProbeLocationName) (temperatureProbeLocationName{temperatureProbeIndex=\"2\"}))",
     "legendFormat": "{{temperatureProbeLocationName}}"
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "coolingDeviceReading{hostname=\"$node\"}",
     "legendFormat": "Fan {{coolingDeviceIndex}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "(physicalDiskCapacityInMB{hostname=\"$node\"}) + on (physicalDiskNumber) group_left(physicalDiskDisplayName) (physicalDiskDisplayName{hostname=\"$node\"}) + on (physicalDiskNumber) group_left(physicalDiskProductID) (physicalDiskProductID{hostname=\"$node\"})  + on (physicalDiskNumber) group_left(physicalDiskSerialNo) (physicalDiskSerialNo{hostname=\"$node\"}) "
    },
    {
     "expr": "physicalDiskComponentStatus{hostname=\"$node\"}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 21 },
   "targets": [
    {
     "expr": "(networkDeviceFQDD{hostname=\"$node\"}) + on (networkDeviceIndex) group_left (networkDeviceVendorName) (networkDeviceVendorName{hostname=\"$node\"})"
    },
    {
     "expr": "networkDeviceConnectionStatus{hostname=\"$node\"}"
    }
   ]
  }
 ]
}