{
 "title": "Fortigate",
 "description": "NOC LDG",
 "tags": [
  "prometheus",
  "firewall",
  "fortigate",
  "snmp"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "fortigate",
    "query": "label_values(fgSysUpTime,instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "fgSysCpuUsage{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "fgSysMemUsage{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Wan 01 in (Minh Tu) ",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 0 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(ifHCInOctets{instance=~\"$instance\"}[5m]) * on (ifIndex) group_left(ifName) ifName{instance=~\"$instance\",ifName=\"wan1\"} * 8"
    }
   ]
  },
  {
   "title": "Wan 02 in (FPT) ",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 0 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(ifHCInOctets{instance=~\"$instance\"}[5m]) * on (ifIndex) group_left(ifName) ifName{instance=~\"$instance\",ifName=\"wan2\"} * 8"
    }
   ]
  },
  {
   "title": "Wan 03 in (VNPT)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 14, "y": 0 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(ifHCInOctets{instance=~\"$instance\"}[5m]) * on (ifIndex) group_left(ifName) ifName{instance=~\"$instance\",ifName=\"port1\"} * 8"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "fgSysUpTime{instance=~\"$instance\"}/100"
    }
   ]
  },
  {
   "title": "Wan 01 out (Minh Tu)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 2 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{instance=~\"$instance\"}[5m]) * on (ifIndex) group_left(ifName) ifName{instance=~\"$instance\",ifName=\"wan1\"} * 8"
    }
   ]
  },
  {
   "title": "Wan 02 out (FPT)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 2 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{instance=~\"$instance\"}[5m]) * on (ifIndex) group_left(ifName) ifName{instance=~\"$instance\",ifName=\"wan2\"} * 8"
    }
   ]
  },
  {
   "title": "Wan 02 out (VNPT)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 14, "y": 2 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{instance=~\"$instance\"}[5m]) * on (ifIndex) group_left(ifName) ifName{instance=~\"$instance\",ifName=\"port1\"} * 8"
    }
   ]
  },
  {
   "title": "OS Version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 2 },
   "format": "short",
   "valueName": "name",
   "targets": [
    {
     "expr": "fgSysVersion{instance=~\"$instance\"}",
     "legendFormat": "{{fgSysVersion}}"
    }
   ]
  },
  {
   "title": "Top 10 Interfaces Bytes/sec IN",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "topk(6,irate( ifHCInOctets{job=\"fortigate\"}[5m]) * on (ifIndex) group_left(ifName) ifName{job=\"fortigate\"} * 8)",
     "legendFormat": "{{ifName}}"
    }
   ]
  },
  {
   "title": "Top 10 Interfaces Bytes/sec OUT",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "topk(6,irate( ifHCOutOctets{job=\"fortigate\"}[5m]) * on (ifIndex) group_left(ifName) ifName{job=\"fortigate\"} *  8)",
     "legendFormat": "{{ifName}}"
    }
   ]
  },
  {
   "title": "Connections FortiVPN Actives",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "fgVpnSslTunnelUpTime{instance=~\"$instance\"}\n\n* on (fgVpnSslTunnelIndex) group_left( fgVpnSslTunnelSrcIp, fgVpnSslTunnelIp, fgVpnSslTunnelUserName ) fgVpnSslTunnelSrcIp{instance=~\"$instance\"}\n\n* on (fgVpnSslTunnelIndex) group_left(fgVpnSslTunnelUserName) fgVpnSslTunnelUserName{instance=~\"$instance\"} \n\n* on (fgVpnSslTunnelIndex) group_left(fgVpnSslTunnelIp ) fgVpnSslTunnelIp{instance=~\"$instance\"}\n"
    },
    {
     "expr": "sum(fgVpnSslTunnelBytesIn{instance=~\"$instance\"}) by (fgVpnSslTunnelIndex)"
    },
    {
     "expr": "sum(fgVpnSslTunnelBytesOut{instance=~\"$instance\"}) by (fgVpnSslTunnelIndex)"
    }
   ]
  }
 ]
}