{
 "title": "IT Overview",
 "description": "NOC LDG",
 "tags": [
  "noc",
  "monitor",
  "prometheus",
  "infra"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "label": "fortigate", "query": "label_values(fgSysUpTime,job)" },
   { "name": "cisco", "label": "cisco", "query": "label_values(sysName,job)" }
  ]
 },
 "panels": [
  {
   "title": "Windows Server Status",
   "type": "table",
   "gridPos": { "h": 14, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"windows\"} == 1 or up{job=\"windows\"} == 0",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "ESXi Host Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "vmware_host_power_state == 1 or vmware_host_power_state == 0",
     "legendFormat": "{{ host_name }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 0 },
   "content": "# INTERNET\nMonitoring bandwidth\n\n\n\n"
  },
  {
   "title": "Top 10 Interfaces Traffic Receive",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "topk(1,rate(ifInOctets{job=\"$cisco\",ifName=~\"(Gi|Te).*\"}[5m])) * 8 ",
     "legendFormat": "{{hostname}} - {{ifName}}"
    }
   ]
  },
  {
   "title": "Wan 01 in (Minh Tu) ",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 2 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(ifHCInOctets{job=\"fortigate\"}[5m]) * on (ifIndex) group_left(ifName) ifName{job=\"fortigate\",ifName=\"wan1\"} * 8"
    }
   ]
  },
  {
   "title": "Wan 01 out (Minh Tu)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 4 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{job=\"fortigate\"}[5m]) * on (ifIndex) group_left(ifName) ifName{job=\"fortigate\",ifName=\"wan1\"} * 8"
    }
   ]
  },
  {
   "title": "Network Devices Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 5 },
   "targets": [
    {
     "expr": "up{job=\"fortigate\"} == 1 or up{job=\"fortigate\"} == 0",
     "legendFormat": "{{ hostname }}"
    },
    {
     "expr": "up{job=\"cisco\"} == 1 or up{job=\"cisco\"} == 0",
     "legendFormat": "{{hostname}}"
    },
    {
     "expr": "up{job=\"pfsense\"} == 1 or up{job=\"pfsense\"} == 0",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Wan 02 in (FPT) ",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 6 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(ifHCInOctets{job=\"fortigate\"}[5m]) * on (ifIndex) group_left(ifName) ifName{job=\"fortigate\",ifName=\"wan2\"} * 8"
    }
   ]
  },
  {
   "title": "Top 15 Interfaces Traffic Send",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 7 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "topk(1, rate(ifOutOctets{job=\"$cisco\",ifName=~\"(Gi|Te).*\"}[5m])) * 8 ",
     "legendFormat": "{{hostname}} - {{ifName}}"
    }
   ]
  },
  {
   "title": "Wan 02 out (FPT)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 8 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{job=\"fortigate\"}[5m]) * on (ifIndex) group_left(ifName) ifName{job=\"fortigate\",ifName=\"wan2\"} * 8"
    }
   ]
  },
  {
   "title": "Wan 03 in (VNPT)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 10 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(ifHCInOctets{job=\"fortigate\"}[5m]) * on (ifIndex) group_left(ifName) ifName{job=\"fortigate\",ifName=\"port1\"} * 8"
    }
   ]
  },
  {
   "title": "Wan 02 out (VNPT)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 12 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{job=\"fortigate\"}[5m]) * on (ifIndex) group_left(ifName) ifName{job=\"fortigate\",ifName=\"port1\"} * 8"
    }
   ]
  },
  {
   "title": "Interface Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(ifInErrors{job=\"$cisco\",ifName=~\"(Gi|Te).*\"}[5m])",
     "legendFormat": "{{hostname}} - {{ifName}} In"
    },
    {
     "expr": "rate(ifOutErrorss{job=\"$cisco\",ifName=~\"(Gi|Te).*\"}[5m])",
     "legendFormat": "{{hostname}} - {{ifName}} Out"
    }
   ]
  },
  {
   "title": "Discard",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 14 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(ifOutDiscards{job=\"$cisco\",ifName=~\"(Gi|Te).*\"}[5m])",
     "legendFormat": "{{hostname}} - {{ifName}} Out"
    },
    {
     "expr": "rate(ifInDiscards{job=\"$cisco\",ifName=~\"(Gi|Te).*\"}[5m])",
     "legendFormat": "{{hostname}} - {{ifName}} In"
    }
   ]
  }
 ]
}