{
 "title": "Network Devices",
 "tags": [
  "cisco",
  "snmp",
  "prometheus",
  "network"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "name", "label": "Device Name", "query": "label_values(sysName)" },
   {
    "name": "ip",
    "label": "IP address",
    "query": "label_values(sysName{sysName=~\"$name\"},instance)"
   },
   {
    "name": "nic",
    "label": "NIC",
    "query": "label_values(ifInOctets{instance=\"$ip\"},ifName)"
   },
   {
    "name": "host_top_recv",
    "query": "query_result(topk(6, rate(ifInOctets{job=\"cisco\",instance=\"$ip\",ifName=~\"(Gi|Te).*\"}[${__range_s}s] )))"
   },
   {
    "name": "host_top_send",
    "query": "query_result(topk(6, rate(ifOutOctets{job=\"cisco\",instance=\"$ip\",ifName=~\"(Gi|Te).*\"}[${__range_s}s] )))"
   },
   {
    "name": "host_top_dis_send",
    "query": "query_result(topk(6, rate(ifInDiscards{job=\"cisco\",instance=\"$ip\",ifName=~\"(Gi|Te).*\"}[${__range_s}s] )))"
   },
   {
    "name": "host_top_dis_recv",
    "query": "query_result(topk(6, rate(ifOutDiscards{job=\"cisco\",instance=\"$ip\",ifName=~\"(Gi|Te).*\"}[${__range_s}s] )))"
   },
   {
    "name": "host_top_err_recv",
    "query": "query_result(topk(6, rate(ifInErrors{job=\"cisco\",instance=\"$ip\",ifName=~\"(Gi|Te).*\"}[${__range_s}s] )))"
   },
   {
    "name": "host_top_err_send",
    "query": "query_result(topk(6, rate(ifOutErrors{job=\"cisco\",instance=\"$ip\",ifName=~\"(Gi|Te).*\"}[${__range_s}s] )))"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avgBusy1{instance=\"$ip\"}"
    }
   ]
  },
  {
   "title": "Top traffic IN/OUT 5m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(ifInOctets{instance=\"$ip\",ifName=~\"$host_top_recv\"}[5m]) * 8 ",
     "legendFormat": "{{ifName}} In"
    },
    {
     "expr": "rate(ifOutOctets{instance=\"$ip\",ifName=~\"$host_top_send\"}[5m]) * 8 ",
     "legendFormat": "{{ifName}} Out"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "ciscoMemoryPoolUsed{ciscoMemoryPoolType=\"1\",instance=\"$ip\"}/(ciscoMemoryPoolFree{ciscoMemoryPoolType=\"1\",instance=\"$ip\"} + ciscoMemoryPoolUsed{ciscoMemoryPoolType=\"1\",instance=\"$ip\"})"
    }
   ]
  },
  {
   "title": "Traffic Receive",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(ifInOctets{instance=\"$ip\",ifName=~\"$nic\"}[5m]) * 8 ",
     "legendFormat": "{{ifName}} In"
    }
   ]
  },
  {
   "title": "Traffic Send",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(ifOutOctets{instance=\"$ip\",ifName=~\"$nic\"}[5m]) * 8 ",
     "legendFormat": "{{ifName}} Out"
    }
   ]
  },
  {
   "title": "Discard",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(ifOutDiscards{instance=\"$ip\",ifName=~\"$nic\"}[5m])",
     "legendFormat": "{{ifName}} In"
    },
    {
     "expr": "rate(ifInDiscards{instance=\"$ip\",ifName=~\"$nic\"}[5m])",
     "legendFormat": "{{ifName}} Out"
    }
   ]
  },
  {
   "title": "Top Discard",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(ifInDiscards{instance=\"$ip\",ifName=~\"$host_top_dis_recv\"}[5m])",
     "legendFormat": "{{ifName}} In"
    },
    {
     "expr": "rate(ifOutDiscards{instance=\"$ip\",ifName=~\"$host_top_dis_send\"}[5m])",
     "legendFormat": "{{ifName}} Out"
    }
   ]
  },
  {
   "title": "Top Error",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(ifInErrors{instance=\"$ip\",ifName=~\"$host_top_err_recv\"}[5m])",
     "legendFormat": "{{ifName}} In"
    },
    {
     "expr": "rate(ifOutErrors{instance=\"$ip\",ifName=~\"$host_top_err_send\"}[5m])",
     "legendFormat": "{{ifName}} Out"
    }
   ]
  },
  {
   "title": "Error",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(ifOutErrors{instance=\"$ip\",ifName=~\"$nic\"}[5m])",
     "legendFormat": "{{ifName}} In"
    },
    {
     "expr": "rate(ifInErrors{instance=\"$ip\",ifName=~\"$nic\"}[5m])",
     "legendFormat": "{{ifName}} Out"
    }
   ]
  },
  {
   "title": "Interface",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "ifSpeed{instance=\"$ip\",ifName=~\"((Gi|Te).*)\"} +0"
    },
    {
     "expr": "ifInDiscards{instance=\"$ip\",ifName=~\"((Gi|Te).*)\"} +0"
    },
    {
     "expr": "ifAlias{instance=\"$ip\",ifName=~\"((Gi|Te).*)\"} +0"
    }
   ]
  }
 ]
}