{
 "title": "Overview IT",
 "tags": [
  "network",
  "systems",
  "infra"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "fortigate", "query": "label_values(fgSysUpTime,job)" },
   { "name": "cisco", "label": "cisco", "query": "label_values(sysName,job)" }
  ]
 },
 "panels": [
  {
   "title": "Minh Tu",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{job=\"fortigate\"}[5m]) * on (ifIndex) group_left(ifName) ifName{job=\"fortigate\",ifName=\"wan1\"} * 8",
     "legendFormat": "Download"
    },
    {
     "expr": "irate(ifHCOutOctets{job=\"fortigate\"}[5m]) * on (ifIndex) group_left(ifName) ifName{job=\"fortigate\",ifName=\"wan1\"} * 8",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "FPT",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{job=\"fortigate\"}[5m]) * on (ifIndex) group_left(ifName) ifName{job=\"fortigate\",ifName=\"wan2\"} * 8",
     "legendFormat": "Download"
    },
    {
     "expr": "irate(ifHCOutOctets{job=\"fortigate\"}[5m]) * on (ifIndex) group_left(ifName) ifName{job=\"fortigate\",ifName=\"wan2\"} * 8",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "VNPT",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{job=\"fortigate\"}[5m]) * on (ifIndex) group_left(ifName) ifName{job=\"fortigate\",ifName=\"port1\"} * 8",
     "legendFormat": "Download"
    },
    {
     "expr": "irate(ifHCOutOctets{job=\"fortigate\"}[5m]) * on (ifIndex) group_left(ifName) ifName{job=\"fortigate\",ifName=\"port1\"} * 8",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Overview Windows",
   "type": "table",
   "gridPos": { "h": 17, "w": 10, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{job=\"windows\",mode=\"idle\"}[2m])) * 100)"
    },
    {
     "expr": "100 - 100 * windows_os_physical_memory_free_bytes{job=\"windows\"} / windows_cs_physical_memory_bytes{job=\"windows\"}"
    },
    {
     "expr": "max by (instance) (1-windows_logical_disk_free_bytes/windows_logical_disk_size_bytes)"
    },
    {
     "expr": "up{job=\"windows\"} == 1 or up{job=\"windows\"} == 0"
    }
   ]
  },
  {
   "title": "Overview Linux",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 4 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{job=\"windows\",mode=\"idle\"}[2m])) * 100)"
    },
    {
     "expr": "100 - 100 * windows_os_physical_memory_free_bytes{job=\"windows\"} / windows_cs_physical_memory_bytes{job=\"windows\"}"
    },
    {
     "expr": "max by (instance) (1-windows_logical_disk_free_bytes/windows_logical_disk_size_bytes)"
    },
    {
     "expr": "up{job=\"windows\"} == 1 or up{job=\"windows\"} == 0"
    }
   ]
  },
  {
   "title": "Cisco",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 4 },
   "targets": [
    {
     "expr": "up{job=\"cisco\"} == 1 or up{job=\"cisco\"} == 0",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "ESXi",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 11 },
   "targets": [
    {
     "expr": "vmware_host_power_state == 1 or vmware_host_power_state == 0",
     "legendFormat": "{{ host_name }}"
    }
   ]
  },
  {
   "title": "Fortigate",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 11 },
   "targets": [
    {
     "expr": "up{job=\"fortigate\"} == 1 or up{job=\"fortigate\"}",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "pfSense",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 11 },
   "targets": [
    {
     "expr": "up{job=\"pfsense\"} == 1 or up{job=\"pfsense\"} == 0",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "table",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "100 - (windows_logical_disk_free_bytes{job=\"windows\",volume!=\"HarddiskVolume1\"} / windows_logical_disk_size_bytes{job=\"windows\",volume!=\"HarddiskVolume1\"})*100"
    },
    {
     "expr": "windows_logical_disk_free_bytes{job=\"windows\",volume!=\"HarddiskVolume1\"}"
    }
   ]
  },
  {
   "title": "Top Ram utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk (5, (100 - 100 * windows_os_physical_memory_free_bytes{job=\"windows\"} / windows_cs_physical_memory_bytes{job=\"windows\"}))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Top CPU utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk (5, 100 - (avg by (hostname) ((irate(windows_cpu_time_total{job=\"windows\",mode=\"idle\"}[5m]) * 100))))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Top local interface traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "topk(5,rate(ifInOctets{job=\"$cisco\",ifName=~\"(Gi|Te).*\"}[5m])) * 8 ",
     "legendFormat": "Receive - {{hostname}} - {{ifName}}"
    },
    {
     "expr": "topk(5, rate(ifOutOctets{job=\"$cisco\",ifName=~\"(Gi|Te).*\"}[5m])) * 8 ",
     "legendFormat": "Send - {{hostname}} - {{ifName}}"
    }
   ]
  },
  {
   "title": "Discard",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(ifOutDiscards{job=\"$cisco\",ifName=~\"(Gi|Te).*\"}[5m])",
     "legendFormat": "{{hostname}} - {{ifName}} Out"
    },
    {
     "expr": "rate(ifInDiscards{job=\"$cisco\",ifName=~\"(Gi|Te).*\"}[5m])",
     "legendFormat": "{{hostname}} - {{ifName}} In"
    }
   ]
  },
  {
   "title": "Interface Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(ifInErrors{job=\"$cisco\",ifName=~\"(Gi|Te).*\"}[5m])",
     "legendFormat": "{{hostname}} - {{ifName}} In"
    },
    {
     "expr": "rate(ifOutErrorss{job=\"$cisco\",ifName=~\"(Gi|Te).*\"}[5m])",
     "legendFormat": "{{hostname}} - {{ifName}} Out"
    }
   ]
  }
 ]
}