{
 "title": "Pfsense",
 "description": "Dashboard for Prometheus node_exporter on FreeBSD",
 "tags": [
  "System",
  "firewall",
  "pfsense",
  "freebsd"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Host:",
    "query": "label_values(node_time, instance)"
   },
   {
    "name": "port",
    "label": "port",
    "query": "label_values(node_time, instance)"
   },
   { "name": "interval", "label": "interval", "query": "30s,1m,5m,1h,6h,1d" },
   {
    "name": "cpus",
    "label": "cpus",
    "query": "label_values(node_cpu_seconds_total{instance=~\"$instance:.+\",job=~\"node_$instance\"}, cpu)"
   },
   {
    "name": "mountpoint",
    "label": "mountpoint",
    "query": "label_values(node_filesystem_size{instance=~\"$instance:$port\"}, mountpoint)"
   }
  ]
 },
 "panels": [
  {
   "title": "Basic CPU / Mem / Disk Gauge $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "CPU Busy $instance",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\",instance=~\"$instance:$port\"}[30s])) / count(count(node_cpu_seconds_total{instance=~\"$instance:$port\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Net err/drops / sec $instance",
   "type": "singlestat",
   "description": "Network errors/drops per second",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "pps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_drop{instance=~\"$instance:$port\"}[$interval])) + sum(rate(node_network_transmit_drop{instance=~\"$instance:$port\"}[$interval])) + sum(rate(node_network_receive_errs{instance=~\"$instance:$port\"}[$interval])) + sum(rate(node_network_transmit_errs{instance=~\"$instance:$port\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Used RAM $instance",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((node_memory_active_bytes{instance=~\"$instance:$port\"} + node_memory_wired_bytes{instance=~\"$instance:$port\"}) / node_memory_size_bytes{instance=~\"$instance:$port\"}) * 100"
    }
   ]
  },
  {
   "title": "Normalised LA (1m avg) $instance",
   "type": "singlestat",
   "description": "LA / CPU count (1 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load1{instance=~\"$instance:$port\"} / scalar(count(count(node_cpu_seconds_total{instance=~\"$instance:$port\"}) by (cpu)))"
    }
   ]
  },
  {
   "title": "Normalised LA (5m avg) $instance",
   "type": "singlestat",
   "description": "LA / CPU count (5 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load5{instance=~\"$instance:$port\"} / scalar(count(count(node_cpu_seconds_total{instance=~\"$instance:$port\"}) by (cpu)))"
    }
   ]
  },
  {
   "title": "Normalised LA (15m avg) $instance",
   "type": "singlestat",
   "description": "LA / CPU count (15m avg)",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load15{instance=~\"$instance:$port\"} / scalar(count(count(node_cpu_seconds_total{instance=~\"$instance:$port\"}) by (cpu)))"
    }
   ]
  },
  {
   "title": "Basic CPU / Mem / Disk Info $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }
  },
  {
   "title": "CPU Cores $instance",
   "type": "singlestat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$instance:$port\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Total RAM $instance",
   "type": "singlestat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_size_bytes{instance=~\"$instance:$port\"}"
    }
   ]
  },
  {
   "title": "Total SWAP $instance",
   "type": "singlestat",
   "description": "Total SWAP",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_swap_size_bytes{instance=~\"$instance:$port\"}"
    }
   ]
  },
  {
   "title": "Total RootFS $instance",
   "type": "singlestat",
   "description": "Total RootFS",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_size{instance=~\"$instance:$port\",mountpoint=~\"/\"}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Network Traffic / sec $instance",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes{instance=~\"$instance:$port\"}[$interval]) * 8 > 0",
     "legendFormat": "{{device}} recv"
    },
    {
     "expr": "rate(node_network_transmit_bytes{instance=~\"$instance:$port\"}[$interval]) * 8 > 0",
     "legendFormat": "{{device}} trans"
    }
   ]
  },
  {
   "title": "Network packets / sec $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_packets{instance=~\"$instance:$port\"}[$interval]) > 0",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_packets{instance=~\"$instance:$port\"}[$interval]) > 0",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Packets drops / sec $instance",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_drop{instance=~\"$instance:$port\"}[$interval]) > 0",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_drop{instance=~\"$instance:$port\"}[$interval]) > 0",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Network Errors / sec $instance",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_errs{instance=~\"$instance:$port\"}[$interval]) > 0",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_errs{instance=~\"$instance:$port\"}[$interval]) > 0",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  { "title": "System Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Context switches / sec $instance",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(node_exec_context_switches_total{instance=~\"$instance:$port\"}[$interval])",
     "legendFormat": "Context switches"
    }
   ]
  },
  {
   "title": "Device interrupts / sec $instance",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(node_exec_device_interrupts_total{instance=~\"$instance:$port\"}[$interval])",
     "legendFormat": "Device interrupts"
    }
   ]
  },
  {
   "title": "Software interrupts / sec $instance",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(node_exec_software_interrupts_total{instance=~\"$instance:$port\"}[$interval])",
     "legendFormat": "Software interrupts"
    }
   ]
  },
  {
   "title": "Exec forks() / sec $instance",
   "type": "graph",
   "description": "Number of fork() calls / sec",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(node_exec_forks_total{instance=~\"$instance:$port\"}[$interval])",
     "legendFormat": "Forks"
    }
   ]
  },
  {
   "title": "Traps / sec $instance",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(node_exec_traps_total{instance=~\"$instance:$port\"}[$interval])",
     "legendFormat": "Traps"
    }
   ]
  },
  {
   "title": "System calls / sec $instance",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(node_exec_system_calls_total{instance=~\"$instance:$port\"}[$interval])",
     "legendFormat": "Syscalls"
    }
   ]
  }
 ]
}