{
 "title": "SQL Server Overview",
 "description": "Prometheus dashboard for Microsoft SQL Server",
 "tags": [
  "prometheus",
  "sql server",
  "database",
  "wmi"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   {
    "name": "server",
    "label": "Sql Server",
    "query": "label_values(wmi_mssql_collector_duration_seconds,instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "% Processor Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (irate(wmi_cpu_time_total{instance=\"$server\", mode!=\"idle\"}[5m])) / count (wmi_cpu_time_total{instance=\"$server\",mode=\"idle\"}) * 100"
    }
   ]
  },
  {
   "title": "Processor Queue Length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "wmi_system_processor_queue_length{instance=\"$server\"}"
    }
   ]
  },
  {
   "title": "Physical Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "wmi_os_visible_memory_bytes{instance=\"$server\"}  \n",
     "legendFormat": "Total"
    },
    {
     "expr": "wmi_os_visible_memory_bytes{instance=\"$server\"} - wmi_os_physical_memory_free_bytes{instance=\"$server\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Paging File usage %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(wmi_os_paging_limit_bytes{instance=\"$server\"} - wmi_os_paging_free_bytes{instance=\"$server\"}) / wmi_os_paging_limit_bytes{instance=\"$server\"}"
    }
   ]
  },
  {
   "title": "Network interface rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(wmi_net_bytes_total{instance=\"$server\"}[5m])",
     "legendFormat": "{{ nic }}"
    }
   ]
  },
  {
   "title": "Percent Disk Busy",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1-rate(wmi_logical_disk_idle_seconds_total{instance=\"$server\"}[5m])",
     "legendFormat": "{{ volume }}"
    }
   ]
  },
  {
   "title": "Disk Reads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(wmi_logical_disk_reads_total{instance=\"$server\"}[5m])",
     "legendFormat": "{{ volume }}"
    }
   ]
  },
  {
   "title": "Disk Writes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(wmi_logical_disk_writes_total{instance=\"$server\"}[5m])",
     "legendFormat": "{{ volume }}"
    }
   ]
  },
  {
   "title": "SQLServer:General Statistics/Processes blocked",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "wmi_mssql_genstats_blocked_processes{instance=\"$server\"} "
    }
   ]
  },
  {
   "title": "SQLServer:Access Methods/Forwarded Records",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(wmi_mssql_accessmethods_forwarded_records{instance=\"$server\"}[5m])"
    }
   ]
  },
  {
   "title": "SQLServer:Access Methods/Page Splits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(wmi_mssql_accessmethods_page_splits{instance=\"$server\"}[5m])"
    }
   ]
  },
  {
   "title": "SQLServer:Buffer Manager/Page life expectancy",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "wmi_mssql_bufman_page_life_expectancy_seconds{instance=\"$server\"} "
    }
   ]
  },
  {
   "title": "SQLServer:SQL Statistics/SQL Compilations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(wmi_mssql_sqlstats_sql_compilations{instance=\"$server\"}[5m])",
     "legendFormat": "Compilations"
    },
    {
     "expr": "irate(wmi_mssql_sqlstats_sql_recompilations{instance=\"$server\"}[5m])",
     "legendFormat": "Recompilations"
    }
   ]
  },
  {
   "title": "About ",
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "content": "Overview of SQL server Performance.\n\nMetrics were inspired by [15 SQL Server Performace Counters to Monitor](https://blogs.sentryone.com/allenwhite/sql-server-performance-counters-to-monitor/)"
  }
 ]
}