{
 "title": "VMware ESXi",
 "description": "VMware ESXi single instance graphs.",
 "tags": [
  "prometheus",
  "vmware",
  "esxi"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "ESXi Host",
    "query": "label_values(vmware_host_connection_state,instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cpu Number",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(vmware_host_num_cpu{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "ESXi host uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "vmware_host_boot_timestamp_seconds{instance=~\"$instance\"} / 32"
    }
   ]
  },
  {
   "title": "Host Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(vmware_host_memory_usage{instance=~\"$instance\"}) * 100 / (vmware_host_memory_max{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Datastores Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "((vmware_datastore_capacity_size{instance=~\"$instance\"}) - (vmware_datastore_freespace_size{instance=~\"$instance\"})) * 100 / (vmware_datastore_capacity_size{instance=~\"$instance\"})",
     "legendFormat": "{{ds_name}}"
    }
   ]
  },
  {
   "title": "Memory Capaciy",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "format": "decmbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(vmware_host_memory_max{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "format": "short",
   "valueName": "name",
   "targets": [
    {
     "expr": "(vmware_host_product_info{instance=~\"$instance\"})",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Model",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "(vmware_host_hardware_info{instance=~\"$instance\"}) ",
     "legendFormat": "{{ hardware_model }}"
    }
   ]
  },
  {
   "title": "Host CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(vmware_host_cpu_usage{instance=~\"$instance\"}) * 100 / (vmware_host_cpu_max{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "VM Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "rate(vmware_vm_mem_usage_average{instance=~\"$instance\"}[5m]) / 4",
     "legendFormat": "{{ vm_name }}"
    }
   ]
  },
  {
   "title": "VM CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "rate(vmware_vm_cpu_usagemhz_average{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{ vm_name }}"
    }
   ]
  }
 ]
}